### ISSUE TITLE
Beheading no longer works

### ISSUE THREAD

**Issue by jlipmabn** [mcolen/headless-hunt#11] opened 2022-03-08 15:11 UTC
Beheading no longer works on crossword screen. Looks like there is a new welcome screen to the crossword, which likely corresponds with a slight site redesign that bricks the extension. See screenshots.

[https://drive.google.com/drive/folders/1Quh1gWryBt0dWyYrQovKRukvquIe8X9O?usp=sharing](See screenshots here)

**Comment by mcolen** [comment] 2022-03-16 05:00
I can't reproduce this. It works fine for me at https://www.nytimes.com/crosswords/game/daily/2022/03/16.

Reminder to self: cancel weekly Games subscription once this issue is closed.

**Comment by mcolen** [comment] 2022-03-23 23:01
Finally was able to reproduce. Should be fixed by this: https://github.com/mcolen/headless-hunt/commit/504de6ec4009de44f7090765a1b60f097181610b.

The extension update needs to undergo review and then will be published. The fix is in v0.6.

**Comment by mcolen** [comment] 2022-03-24 16:21
Version 0.6 is now available on the chrome web store.

**Closed by mcolen** 2022-03-24 16:21 UTC
